<?php
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class AllSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // TABLE KABUPATEN/KOTA
        DB::table('tb_kabupatenkota')->insert(array(
          array('nama_kabupatenkota' => 'Badung'),
          array('nama_kabupatenkota' => 'Bangli'),
          array('nama_kabupatenkota' => 'Buleleng'),
          array('nama_kabupatenkota' => 'Denpasar'),
          array('nama_kabupatenkota' => 'Gianyar'),
          array('nama_kabupatenkota' => 'Jembrana'),
          array('nama_kabupatenkota' => 'Karangasem'),
          array('nama_kabupatenkota' => 'Klungkung'),
          array('nama_kabupatenkota' => 'Tabanan')
        ));

        // TABLE KECAMATAN
        DB::table('tb_kecamatan')->insert(array(

          // BADUNG
          array('nama_kecamatan' => 'Abiansemal', 'id_kabupatenkota' => 1),
          array('nama_kecamatan' => 'Kuta', 'id_kabupatenkota' => 1),
          array('nama_kecamatan' => 'Kuta Selatan', 'id_kabupatenkota' => 1),
          array('nama_kecamatan' => 'Kuta Utara', 'id_kabupatenkota' => 1),
          array('nama_kecamatan' => 'Mengwi', 'id_kabupatenkota' => 1),
          array('nama_kecamatan' => 'Petang', 'id_kabupatenkota' => 1),

          // BANGLI
          array('nama_kecamatan' => 'Bangli', 'id_kabupatenkota' => 2),
          array('nama_kecamatan' => 'Kintamani', 'id_kabupatenkota' => 2),
          array('nama_kecamatan' => 'Susut', 'id_kabupatenkota' => 2),
          array('nama_kecamatan' => 'Tembuku', 'id_kabupatenkota' => 2),

          // BULELENG
          array('nama_kecamatan' => 'Banjar', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Buleleng', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Busungbiu', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Gerokgak', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Kubutambahan', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Sawan', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Seririt', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Sukasada', 'id_kabupatenkota' => 3),
          array('nama_kecamatan' => 'Tejakula', 'id_kabupatenkota' => 3),

          // DENPASAR
          array('nama_kecamatan' => 'Denpasar Barat', 'id_kabupatenkota' => 4),
          array('nama_kecamatan' => 'Denpasar Selatan', 'id_kabupatenkota' => 4),
          array('nama_kecamatan' => 'Denpasar Timur', 'id_kabupatenkota' => 4),
          array('nama_kecamatan' => 'Denpasar Utara', 'id_kabupatenkota' => 4),

          // GIANYAR
          array('nama_kecamatan' => 'Blahbatuh', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Gianyar', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Payangan', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Sukawati', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Tampak Siring', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Tegallalang', 'id_kabupatenkota' => 5),
          array('nama_kecamatan' => 'Ubud', 'id_kabupatenkota' => 5),

          // JEMBRANA
          array('nama_kecamatan' => 'Jembrana', 'id_kabupatenkota' => 6),
          array('nama_kecamatan' => 'Melaya', 'id_kabupatenkota' => 6),
          array('nama_kecamatan' => 'Mendoyo', 'id_kabupatenkota' => 6),
          array('nama_kecamatan' => 'Negara', 'id_kabupatenkota' => 6),
          array('nama_kecamatan' => 'Pekutatan', 'id_kabupatenkota' => 6),

          // KARANGASEM
          array('nama_kecamatan' => 'Abang', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Bebandem', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Karang Asem', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Kubu', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Manggis', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Rendang', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Selat', 'id_kabupatenkota' => 7),
          array('nama_kecamatan' => 'Sidemen', 'id_kabupatenkota' => 7),

          // KLUNGKUNG
          array('nama_kecamatan' => 'Banjarangkan', 'id_kabupatenkota' => 8),
          array('nama_kecamatan' => 'Dawan', 'id_kabupatenkota' => 8),
          array('nama_kecamatan' => 'Klungkung', 'id_kabupatenkota' => 8),
          array('nama_kecamatan' => 'Nusapenida', 'id_kabupatenkota' => 8),

          // TABANAN
          array('nama_kecamatan' => 'Baturiti', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Kediri', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Kerambitan', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Marga', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Penebel', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Pupuan', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Selemadeg Barat', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Selemadeg Timur', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Selemadeg', 'id_kabupatenkota' => 9),
          array('nama_kecamatan' => 'Tabanan', 'id_kabupatenkota' => 9),

        ));

        // TABLE DESA
        DB::table('tb_kelurahandesa')->insert(array(
          // ABIANSEMAL (BADUNG)
          array('nama_kelurahandesa' => 'Abiansemal', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Angantaka', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Ayunan', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Blahkiuh', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Bongkasa', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Bongkasa Pertiwi', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Darmasaba', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Dauh Yeh Cani', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Jagapati', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Mambal', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Mekar Bhuwana', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Punggul', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Sangeh', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Sedang', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Selat', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Sibang Gede', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Sibang Kaja', 'id_kecamatan' => 1),
          array('nama_kelurahandesa' => 'Taman', 'id_kecamatan' => 1),

          // KUTA (BADUNG)
          array('nama_kelurahandesa' => 'Kedonganan', 'id_kecamatan' => 2),
          array('nama_kelurahandesa' => 'Kuta', 'id_kecamatan' => 2),
          array('nama_kelurahandesa' => 'Legian', 'id_kecamatan' => 2),
          array('nama_kelurahandesa' => 'Seminyak', 'id_kecamatan' => 2),
          array('nama_kelurahandesa' => 'Tuban', 'id_kecamatan' => 2),

          // KUTA SELATAN (BADUNG)
          array('nama_kelurahandesa' => 'Benoa', 'id_kecamatan' => 3),
          array('nama_kelurahandesa' => 'Jimbaran', 'id_kecamatan' => 3),
          array('nama_kelurahandesa' => 'Kutuh', 'id_kecamatan' => 3),
          array('nama_kelurahandesa' => 'Pecatu', 'id_kecamatan' => 3),
          array('nama_kelurahandesa' => 'Tanjung Benoa', 'id_kecamatan' => 3),
          array('nama_kelurahandesa' => 'Ungasan', 'id_kecamatan' => 3),

          // KUTA UTARA (BADUNG)
          array('nama_kelurahandesa' => 'Canggu', 'id_kecamatan' => 4),
          array('nama_kelurahandesa' => 'Dalung', 'id_kecamatan' => 4),
          array('nama_kelurahandesa' => 'Kerobokan', 'id_kecamatan' => 4),
          array('nama_kelurahandesa' => 'Kerobokan Kaja', 'id_kecamatan' => 4),
          array('nama_kelurahandesa' => 'Kerobokan Kelod', 'id_kecamatan' => 4),
          array('nama_kelurahandesa' => 'Tibubeneng', 'id_kecamatan' => 4),

          // MENGWI (BADUNG)
          array('nama_kelurahandesa' => 'Abianbase', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Baha', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Buduk', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Cemagi', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Gulingan', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Kapal', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Kekeran', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Kuwum', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Lukluk', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Mengwi', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Mengwitani', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Munggu', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Penarungan', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Pererenan', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Sading', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Sembung', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Sempidi', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Sobangan', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Tumbak Bayuh', 'id_kecamatan' => 5),
          array('nama_kelurahandesa' => 'Werdi Bhuawana', 'id_kecamatan' => 5),

          // PETANG (BADUNG)
          array('nama_kelurahandesa' => 'Belok', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Carangsari', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Getasan', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Pangsan', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Pelaga', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Petang', 'id_kecamatan' => 6),
          array('nama_kelurahandesa' => 'Sulangai', 'id_kecamatan' => 6),

          // BANGLI (BANGLI)
          array('nama_kelurahandesa' => 'Bebalang', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Bunutin', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Cempaga', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Kawan', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Kayubihi', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Kubu', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Landih', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Pengotan', 'id_kecamatan' => 7),
          array('nama_kelurahandesa' => 'Taman Bali', 'id_kecamatan' => 7),

          // KINTAMANI (BANGLI)
          array('nama_kelurahandesa' => 'Abang Songan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Abuan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Awan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Bantang', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Banua', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Batu Dinding', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Batukaang', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Batur Selatan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Batur Tengah', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Batur Utara', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Bayungcerik', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Bayunggede', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Belancan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Belandingan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Belanga', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Belantih', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Binyan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Bonyoh', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Buahan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Bunutin', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Catur', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Daup', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Dausa', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Gunungbau', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Katung', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Kedisan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Kintamani', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Kutuh', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Langgahan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Lembean', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Mangguh', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Manikliyu', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Mengani', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Pengejaran', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Pinggan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Satra', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Sekaan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Sekardadi', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Selulung', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Serahi', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Siyakin', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Songan A', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Songan B', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Subaya', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Sukawana', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Suter', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Terunyan', 'id_kecamatan' => 8),
          array('nama_kelurahandesa' => 'Ulian', 'id_kecamatan' => 8),

          // SUSUT (BANGLI)
          array('nama_kelurahandesa' => 'Abuan', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Apuan', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Demulih', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Pengiangan', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Penglumbaran', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Selat', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Sulahan', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Susut', 'id_kecamatan' => 9),
          array('nama_kelurahandesa' => 'Tiga', 'id_kecamatan' => 9),

          // TEMBUKU (BANGLI)
          array('nama_kelurahandesa' => 'Bangbang', 'id_kecamatan' => 10),
          array('nama_kelurahandesa' => 'Jehem', 'id_kecamatan' => 10),
          array('nama_kelurahandesa' => 'Peninjoan', 'id_kecamatan' => 10),
          array('nama_kelurahandesa' => 'Tembuku', 'id_kecamatan' => 10),
          array('nama_kelurahandesa' => 'Undisan', 'id_kecamatan' => 10),
          array('nama_kelurahandesa' => 'Yangapi', 'id_kecamatan' => 10),

          // BANJAR (BULELENG)
          array('nama_kelurahandesa' => 'Banjar', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Banjar Tegeha', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Banyuatis', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Banyusri', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Cempaga', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Dencarik', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Gesing', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Gobleg', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Kaliasem', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Kayuputih', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Munduk', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Pedawa', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Sidetapa', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Tampekan', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Temukus', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Tigawasa', 'id_kecamatan' => 11),
          array('nama_kelurahandesa' => 'Tirtasari', 'id_kecamatan' => 11),

          // BULELENG (BULELENG)
          array('nama_kelurahandesa' => 'Alasangker', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Anturan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Astina', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Banjar Bali', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Banjar Jawa', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Banjar Tegal', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Banyuasri', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Banyuning', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Beratan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Bakti Seraga', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Jinengdalem', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kalibukbuk', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kaliuntu', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kampung Anyar', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kampung Baru', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kampung Bugis', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kampung Kajanan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kampung Singaraja', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Kendran', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Liligundi', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Nagasepaha', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Paket Agung', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Pemaron', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Penarukan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Penglatan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Petandakan', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Poh Bergong', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Sari Mekar', 'id_kecamatan' => 12),
          array('nama_kelurahandesa' => 'Tukadmungga', 'id_kecamatan' => 12),

          // BUSUNGBIU (BULELENG)
          array('nama_kelurahandesa' => 'Bengkel', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Bongancina', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Busungbiu', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Kedis', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Kekeran', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Pelapuan', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Pucaksari', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Sepang', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Sepang Kelod', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Subuk', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Telaga', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Tinggarsari', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Tista', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Titab', 'id_kecamatan' => 13),
          array('nama_kelurahandesa' => 'Umejero', 'id_kecamatan' => 13),

          // GEROKGAK (BULELENG)
          array('nama_kelurahandesa' => 'Banyupoh', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Celukan Bawang', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Gerokgak', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Musi', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Patas', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Pejarakan', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Pemuteran', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Pengulon', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Penyabangan', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Sanggalangit', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Sumber Klampok', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Sumberkima', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Tinga Tinga', 'id_kecamatan' => 14),
          array('nama_kelurahandesa' => 'Tukad Sumaga', 'id_kecamatan' => 14),

          // KUBUTAMBAHAN (BULELENG)
          array('nama_kelurahandesa' => 'Bengkala', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Bila', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Bontihing', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Bukti', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Bulian', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Depeha', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Kubutambahan', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Mengening', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Pakisan', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Tajun', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Tambakan', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Tamblang', 'id_kecamatan' => 15),
          array('nama_kelurahandesa' => 'Tunjung', 'id_kecamatan' => 15),

          // SAWAN (BULELENG)
          array('nama_kelurahandesa' => 'Bebetin', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Bungkulan', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Galungan', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Giri Emas', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Jagaraga', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Kerobokan', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Lemukih', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Menyali', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Sangsit', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Sawan', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Sekumpul', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Sinabun', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Sudaji', 'id_kecamatan' => 16),
          array('nama_kelurahandesa' => 'Suwug', 'id_kecamatan' => 16),

          // SERIRIT (BULELENG)
          array('nama_kelurahandesa' => 'Banjar Asem', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Bestala', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Bubunan', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Gunungsari', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Joanyar', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Kalianget', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Kalisada', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Lokapaksa', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Mayong', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Munduk Bestala', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Pangkungparuk', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Patemon', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Pengastulan', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Rangdu', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Ringdikit', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Seririt', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Sulanyah', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Tangguwisia', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Ularan', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Umeanyar', 'id_kecamatan' => 17),
          array('nama_kelurahandesa' => 'Unggahan', 'id_kecamatan' => 17),

          // SUKASADA (BULELENG)
          array('nama_kelurahandesa' => 'Ambengan', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Gitgit', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Kayuputih', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Padangbulia', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Pancasari', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Panji', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Panji Anom', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Pegadungan', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Pegayaman', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Sambangan', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Selat', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Silangjana', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Sukasada', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Tegal Linggah', 'id_kecamatan' => 18),
          array('nama_kelurahandesa' => 'Wanagiri', 'id_kecamatan' => 18),

          // TEJAKULA (BULELENG)
          array('nama_kelurahandesa' => 'Bondalem', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Julah', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Les', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Madenan', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Pacung', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Penuktukan', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Sambirenteng', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Sembiran', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Tejakula', 'id_kecamatan' => 19),
          array('nama_kelurahandesa' => 'Tembok', 'id_kecamatan' => 19),

          // DENPASAR BARAT (DENPASAR)
          array('nama_kelurahandesa' => 'Dauh Puri', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Dauh Puri Kangin', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Dauh Puri Kauh', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Dauh Puri Kelod', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Padangsambian', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Padangsambian Kaja', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Padangsambian Kelod', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Pemecutan', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Pemecutan Kelod', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Tegal Harum', 'id_kecamatan' => 20),
          array('nama_kelurahandesa' => 'Tegal Kertha', 'id_kecamatan' => 20),

          // DENPASAR SELATAN (DENPASAR)
          array('nama_kelurahandesa' => 'Panjer', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Pedungan', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Pemogan', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Renon', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Sanur', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Sanur Kaja', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Sanur Kauh', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Serangan', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Sesetan', 'id_kecamatan' => 21),
          array('nama_kelurahandesa' => 'Sidakarya', 'id_kecamatan' => 21),

          // DENPASAR TIMUR (DENPASAR)
          array('nama_kelurahandesa' => 'Dangin Puri', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Dangin Puri Klod', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Kesiman', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Kesiman Kertalangu', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Kesiman Petilan', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Penatih', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Penatih Dangin Puri', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Sumerta', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Sumerta Kaja', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Sumerta Kauh', 'id_kecamatan' => 22),
          array('nama_kelurahandesa' => 'Sumerta Kelod', 'id_kecamatan' => 22),

          // DENPASAR UTARA (DENPASAR)
          array('nama_kelurahandesa' => 'Dangin Puri Kaja', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Dangin Puri Kangin', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Dangin Puri Kauh', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Dauh Puri Kaja', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Peguyangan', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Peguyangan Kaja', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Peguyangan Kangin', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Pemecutan Kaja', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Tonja', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Ubung', 'id_kecamatan' => 23),
          array('nama_kelurahandesa' => 'Ubung Kaja', 'id_kecamatan' => 23),

          // BLAHBATUH (GIANYAR)
          array('nama_kelurahandesa' => 'Bedulu', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Belega', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Blahbatuh', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Bona', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Buruan', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Keramas', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Medahan', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Pering', 'id_kecamatan' => 24),
          array('nama_kelurahandesa' => 'Saba', 'id_kecamatan' => 24),

          // GIANYAR (GIANYAR)
          array('nama_kelurahandesa' => 'Abianbase', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Bakbakan', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Beng', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Bitera', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Gianyar', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Lebih', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Petak', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Petak Kaja', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Samplangan', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Serongga', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Siangan', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Sidan', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Sumita', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Suwat', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Tegal Tugu', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Temesi', 'id_kecamatan' => 25),
          array('nama_kelurahandesa' => 'Tulikup', 'id_kecamatan' => 25),

          // PAYANGAN (GIANYAR)
          array('nama_kelurahandesa' => 'Bresela', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Buahan', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Buahan Kaja', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Bukian', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Kelusa', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Kerta', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Melinggih', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Melinggih Kelod', 'id_kecamatan' => 26),
          array('nama_kelurahandesa' => 'Puhu', 'id_kecamatan' => 26),

          // SUKAWATI (GIANYAR)
          array('nama_kelurahandesa' => 'Batuan', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Batuan Kaler', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Batubulan', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Batubulan Kangin', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Celuk', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Guwang', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Kemenuh', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Ketewel', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Singapadu', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Singapadu Kaler', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Singapadu Tengah', 'id_kecamatan' => 27),
          array('nama_kelurahandesa' => 'Sukawati', 'id_kecamatan' => 27),

          // TAMPAK SIRING (GIANYAR)
          array('nama_kelurahandesa' => 'Manukaya', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Pejeng', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Pejeng Kaja', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Pejeng Kangin', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Pejeng Kawan', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Pejeng Kelod', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Sanding', 'id_kecamatan' => 28),
          array('nama_kelurahandesa' => 'Tampaksiring', 'id_kecamatan' => 28),

          // TEGALLALANG (GIANYAR)
          array('nama_kelurahandesa' => 'Kedisan', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Keliki', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Kenderan', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Pupuan', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Sebatu', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Taro', 'id_kecamatan' => 29),
          array('nama_kelurahandesa' => 'Tegallalang', 'id_kecamatan' => 29),

          // UBUD (GIANYAR)
          array('nama_kelurahandesa' => 'Kedewatan', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Lodtunduh', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Mas', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Peliatan', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Petulu', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Sayan', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Singakerta', 'id_kecamatan' => 30),
          array('nama_kelurahandesa' => 'Ubud', 'id_kecamatan' => 30),

          // JEMBRANA (JEMBRANA)
          array('nama_kelurahandesa' => 'Air Kuning', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Batuagung', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Budeng', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Dangin Tukadaya', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Dauhwaru', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Loloan Timur', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Pendem', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Perancak', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Sangkaragung', 'id_kecamatan' => 31),
          array('nama_kelurahandesa' => 'Yeh Kuning', 'id_kecamatan' => 31),

          // MELAYA (JEMBRANA)
          array('nama_kelurahandesa' => 'Blimbingsari', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Candikusuma', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Ekasari', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Gilimanuk', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Manistutu', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Melaya', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Nusa Sari', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Tukadaya', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Tuwed', 'id_kecamatan' => 32),
          array('nama_kelurahandesa' => 'Warnasari', 'id_kecamatan' => 32),

          // MENDOYO (JEMBRANA)
          array('nama_kelurahandesa' => 'Delod Berawah', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Mendoyo Dangin Tukad', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Mendoyo Dauh Tukad', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Penyaringan', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Pergung', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Pohsanten', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Tegal Cangkring', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Yeh Embang', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Yeh Embang Kangin', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Yeh Embang Kauh', 'id_kecamatan' => 33),
          array('nama_kelurahandesa' => 'Yeh Sumbul', 'id_kecamatan' => 33),

          // NEGARA (JEMBRANA)
          array('nama_kelurahandesa' => 'Baler Bale Agung', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Baluk', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Banjar Tengah', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Banyubiru', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Berangbang', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Cupel', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Kaliakah', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Lelateng', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Loloan Barat', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Pengambengan', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Tegal Badeng Barat', 'id_kecamatan' => 34),
          array('nama_kelurahandesa' => 'Tegal Badeng Timur', 'id_kecamatan' => 34),

          // PEKUTATAN (JEMBRANA)
          array('nama_kelurahandesa' => 'Asahduren', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Gumbrih', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Manggissari', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Medewi', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Pangyangan', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Pekutatan', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Pengeragoan', 'id_kecamatan' => 35),
          array('nama_kelurahandesa' => 'Pulukan', 'id_kecamatan' => 35),

          // ABANG (KARANGASEM)
          array('nama_kelurahandesa' => 'Ababi', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Abang', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Bunutan', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Culik', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Datah', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Kerta Mandala', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Kesimpar', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Laba Sari', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Nawakerti', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Pidpid', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Purwakerti', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Tista', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Tiyingtali', 'id_kecamatan' => 36),
          array('nama_kelurahandesa' => 'Tri Buana', 'id_kecamatan' => 36),

          // BEBANDEM (KARANGASEM)
          array('nama_kelurahandesa' => 'Bebandem', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Buana Giri', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Budakeling', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Bungaya', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Bungaya Kangin', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Jungutan', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Macang', 'id_kecamatan' => 37),
          array('nama_kelurahandesa' => 'Sibetan', 'id_kecamatan' => 37),

          // KARANG ASEM (KARANGASEM)
          array('nama_kelurahandesa' => 'Bugbug', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Bukit', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Karangasem', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Padang Kerta', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Pertima', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Seraya Barat', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Seraya Tengah', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Seraya Timur', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Subagan', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Tegallinggah', 'id_kecamatan' => 38),
          array('nama_kelurahandesa' => 'Tumbu', 'id_kecamatan' => 38),

          // KUBU (KARANGASEM)
          array('nama_kelurahandesa' => 'Ban', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Batu Ringgit', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Dukuh', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Kubu', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Sukadana', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Tianyar Barat', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Tianyar Tengah', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Tianyar Timur', 'id_kecamatan' => 39),
          array('nama_kelurahandesa' => 'Tulamben', 'id_kecamatan' => 39),

          // MANGGIS (KARANGASEM)
          array('nama_kelurahandesa' => 'Antiga', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Antiga Kelod', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Gegelang', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Manggis', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Ngis', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Nyuh Tebel', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Padangbai', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Pesedahan', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Selumbung', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Sengkidu', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Tenganan', 'id_kecamatan' => 40),
          array('nama_kelurahandesa' => 'Ulakan', 'id_kecamatan' => 40),


          // RENDANG (KARANGASEM)
          array('nama_kelurahandesa' => 'Besakih', 'id_kecamatan' => 41),
          array('nama_kelurahandesa' => 'Menanga', 'id_kecamatan' => 41),
          array('nama_kelurahandesa' => 'Nongan', 'id_kecamatan' => 41),
          array('nama_kelurahandesa' => 'Pempatan', 'id_kecamatan' => 41),
          array('nama_kelurahandesa' => 'Pesaban', 'id_kecamatan' => 41),
          array('nama_kelurahandesa' => 'Rendang', 'id_kecamatan' => 41),

          // SELAT (KARANGASEM)
          array('nama_kelurahandesa' => 'Amerta Bhuana', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Duda', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Duda Timur', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Duda Utara', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Muncan', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Pering Sari', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Sebudi', 'id_kecamatan' => 42),
          array('nama_kelurahandesa' => 'Selat', 'id_kecamatan' => 42),

          // SIDEMEN (KARANGASEM)
          array('nama_kelurahandesa' => 'Kertha Buana', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Lokasari', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Sangkan Gunung', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Sidemen', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Sindu Wati', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Talibeng', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Tangkup', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Telaga Tawang', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Tri Eka Buana', 'id_kecamatan' => 43),
          array('nama_kelurahandesa' => 'Wisma Kerta', 'id_kecamatan' => 43),

          // BANJARANGKAN (KLUNGKUNG)
          array('nama_kelurahandesa' => 'Aan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Bakas', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Banjarangkan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Bungbungan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Getakan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Negari', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Nyalian', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Nyanglan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Takmung', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Tihingan', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Timuhun', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Tohpati', 'id_kecamatan' => 44),
          array('nama_kelurahandesa' => 'Tusan', 'id_kecamatan' => 44),

          // DAWAN (KLUNGKUNG)
          array('nama_kelurahandesa' => 'Besan', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Dawan Kaler', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Dawan Klod', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Gunaksa', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Kampung Kusamba', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Kusamba', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Paksebali', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Pesinggahan', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Pikat', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Sampalan Klod', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Sampalan Tengah', 'id_kecamatan' => 45),
          array('nama_kelurahandesa' => 'Sulang', 'id_kecamatan' => 45),

          // KLUNGKUNG (KLUNGKUNG)
          array('nama_kelurahandesa' => 'Akah', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Gelgel', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Jumpai', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Kamasan', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Kampung Gelgel', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Manduang', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Satra', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Selat', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Selisihan', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Kaja', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Kangin', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Kauh', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Klod Kangin', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Kelod', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Semarapura Tengah', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Tangkas', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Tegak', 'id_kecamatan' => 46),
          array('nama_kelurahandesa' => 'Tojan', 'id_kecamatan' => 46),

          // NUSA PENIDA (KLUNGKUNG)
          array('nama_kelurahandesa' => 'Batukandik', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Batumadeg', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Batununggul', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Bunga Mekar', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Jungutbatu', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Kampung Toyapakeh', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Klumpu', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Kutampi', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Kutampi Kaler', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Lembongan', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Ped', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Pejukutan', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Sakti', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Sekartaji', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Suana', 'id_kecamatan' => 47),
          array('nama_kelurahandesa' => 'Tanglad', 'id_kecamatan' => 47),

          //BATURITI(TABANAN)
          array('nama_kelurahandesa' => 'Angseri', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Antapan', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Apuan', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Bangli', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Batunya', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Baturiti', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Candikuning', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Luwus', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Mekarsari', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Perean', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Perean Kangin', 'id_kecamatan' => 48),
          array('nama_kelurahandesa' => 'Perean Tengah', 'id_kecamatan' => 48),


          //KEDIRI(TABANAN)
          array('nama_kelurahandesa' => 'Abian Tuwung', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Banjar Anyar', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Belalang', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Bengkel Sari', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Beraban', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Buwit', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Cepaka', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Kaba - Kaba', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Kediri', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Nyambu', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Nyitdah', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Pandak Bandung', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Pandak Gede', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Pangkuang Tibah', 'id_kecamatan' => 49),
          array('nama_kelurahandesa' => 'Pejaten', 'id_kecama tan' => 49),

          //KERAMBITAN(TABANAN)
          array('nama_kelurahandesa' => 'Batuaji', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Baturiti', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Belumbang', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Kelating', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Kerambitan', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Kesiut', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Kukuh', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Meliling', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Pangkung Karung', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Penarukan', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Samsam', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Sembung Gede', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Tibubiyu', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Timpag', 'id_kecamatan' => 50),
          array('nama_kelurahandesa' => 'Tista', 'id_kecamatan' => 50),

          //MARGA(TABANAN)
          array('nama_kelurahandesa' => 'Baru', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Batannyuh', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Beringkit', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Cau Belayu', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Geluntung', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Kukuh', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Kuwum', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Marga', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Marga Dajan Puri', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Marga Dauh Puri', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Payangan', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Peken', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Petiga', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Selanbawak', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Tegaljadi', 'id_kecamatan' => 51),
          array('nama_kelurahandesa' => 'Tua', 'id_kecamatan' => 51),

          //PENEBEL(TABANAN)
          array('nama_kelurahandesa' => 'Babahan', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Biaung', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Buruan', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Jatiluwin', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Jegu', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Mengeste', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Penatahan', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Penebel', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Pesagi', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Pitra', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Rejasa', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Riang Gede', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Sangketan', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Senganan', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Tajen', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Tegalinggah', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Tengkudak', 'id_kecamatan' => 52),
          array('nama_kelurahandesa' => 'Wongaya Gede', 'id_kecamatan' => 52),

          //PUPUAN(TABANAN)
          array('nama_kelurahandesa' => 'Bantiran', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Batungsel', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Belatungan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Belimbing', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Jelijih Punggang', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Karya Sari', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Kebon Padangan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Munduk Temu', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Padangan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Pajahan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Pujungan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Pupuan', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Sai', 'id_kecamatan' => 53),
          array('nama_kelurahandesa' => 'Sanda', 'id_kecamatan' => 53),

          //SELEMADEG BARAT(TABANAN)
          array('nama_kelurahandesa' => 'Angkah', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Antosari', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Bengkel Sari', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Lalang Linggah', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Lumbung', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Lumbung Kauh', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Mundeh', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Mundeh Kangin', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Mundeh Kauh', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Selabih', 'id_kecamatan' => 54),
          array('nama_kelurahandesa' => 'Tiying Gading', 'id_kecamatan' => 54),

          //SELEMADEG TIMUR(TABANAN)
          array('nama_kelurahandesa' => 'Bantas', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Beraban', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Dalang', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Gadung Sari', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Gadungan', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Gunung Salak', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Mambang', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Megati', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Tangguntiti', 'id_kecamatan' => 55),
          array('nama_kelurahandesa' => 'Tegal Mengkeb', 'id_kecamatan' => 55),

          //SELEMADEG(TABANAN)
          array('nama_kelurahandesa' => 'Antap', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Bajera', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Bajera Utara', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Berembeng', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Manikyang', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Pupuan Sawah', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Selemadeg', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Serampingan', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Wanagiri', 'id_kecamatan' => 56),
          array('nama_kelurahandesa' => 'Wanagiri Kauh', 'id_kecamatan' => 56),

          //TABANAN(TABANAN)
          array('nama_kelurahandesa' => 'Bongan', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Buahan', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Dauh Peken', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Dajan Peken', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Delod Peken', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Denbantas', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Gubug', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Sesandan', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Subamia', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Sudimara', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Tunjuk', 'id_kecamatan' => 57),
          array('nama_kelurahandesa' => 'Wanasari', 'id_kecamatan' => 57),









        ));
    }

}
